name: mate-wayland
version: git
summary: A prototype for the MATE desktop running on Wayland with Mir
description: A prototype for the MATE desktop running on Wayland with Mir
confinement: classic
grade: devel
base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  mate-wayland:
    command: bin/desktop-launch $SNAP/bin/mate-wayland.sh
    environment:
      SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}

  mirco:
    command: bin/desktop-launch $SNAP/bin/mirco.sh
    environment:
      SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}

  panel:
    command: bin/desktop-launch $SNAP/bin/panel.sh
    environment:
      SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}

  terminal:
    command: bin/desktop-launch $SNAP/usr/bin/mate-terminal
    desktop: usr/share/applications/mate-terminal.desktop

parts:
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3

  gtk-layer-shell:
    after: [desktop-gtk3]
    plugin: meson
    source: https://github.com/wmww/gtk-layer-shell.git
    source-depth: 1
    build-packages:
      - libwayland-dev
      - gobject-introspection
      - libgirepository1.0-dev
    stage-packages:
      - libwayland-client0

  gtk-layer-background:
    after: [desktop-gtk3, gtk-layer-shell]
    plugin: autotools
    source: https://github.com/wmww/gtk-layer-background.git
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr

  mate-common:
    after: [desktop-gtk3]
    plugin: autotools
    source: https://github.com/mate-desktop/mate-common.git
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
    override-build: |
      snapcraftctl build
      sed -i 's:^prefix=/usr$:prefix=${SNAPCRAFT_STAGE}/usr/:g' ${SNAPCRAFT_PART_INSTALL}/usr/bin/mate-doc-common
    build-environment:
      - ACLOCAL_FLAGS: -I ${SNAPCRAFT_STAGE}/usr/share/aclocal/
    stage-packages:
      - mate-icon-theme
      - adwaita-icon-theme-full

  mate-terminal:
    after: [mate-common]
    plugin: autotools
    source: https://github.com/mate-desktop/mate-terminal.git
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment:
      - ACLOCAL_FLAGS: -I ${SNAPCRAFT_STAGE}/usr/share/aclocal/
    build-packages:
      - libvte-2.91-dev
    stage-packages:
      - libvte-2.91-0

  mate-desktop:
    after: [mate-common]
    plugin: autotools
    source: https://github.com/mate-desktop/mate-desktop.git
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment:
      - ACLOCAL_FLAGS: -I ${SNAPCRAFT_STAGE}/usr/share/aclocal/
    # As of core20, the autotools plugin refuses to run ./autogen.sh anymore
    # ./configure must exist, but it can just be a symlink to ./autogen.sh
    # We remove any old ./configure that may exist so ln doesn't fail
    # If mate-desktop starts providing a ./configre this whole mess can be dropped
    override-build: |
      ln -sf $SNAPCRAFT_PART_BUILD/autogen.sh $SNAPCRAFT_PART_BUILD/configure
      snapcraftctl build
    build-packages:
      - intltool
      - gtk-doc-tools
      - gobject-introspection
      - libdconf-dev
      - libgtk-3-dev
      - iso-codes
      - autoconf-archive
    stage-packages:
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxrandr2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcairo2
      - libcairo-gobject2
      - libepoxy0
      - libgraphite2-3
      - libgdk-pixbuf2.0-0
      - zlib1g
      - libstartup-notification0
      - libx11-xcb1
      - libxcb-util1

  mate-menu:
    plugin: autotools
    after: [mate-common]
    source: https://github.com/mate-desktop/mate-menus.git
    source-depth: 1
    build-environment:
      - ACLOCAL_FLAGS: -I ${SNAPCRAFT_STAGE}/usr/share/aclocal/

  mate-weather:
    plugin: autotools
    after: [mate-common]
    source: https://github.com/mate-desktop/libmateweather.git
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment:
      - ACLOCAL_FLAGS: -I ${SNAPCRAFT_STAGE}/usr/share/aclocal/
    # As of core20, the autotools plugin refuses to run ./autogen.sh anymore
    # ./configure must exist, but it can just be a symlink to ./autogen.sh
    # We remove any old ./configure that may exist so ln doesn't fail
    # If mate-desktop starts providing a ./configre this whole mess can be dropped
    override-build: |
      ln -sf $SNAPCRAFT_PART_BUILD/autogen.sh $SNAPCRAFT_PART_BUILD/configure
      snapcraftctl build
    build-packages:
      - libsoup2.4-dev
      - tzdata
      - libxml2-dev

  mate-panel:
    plugin: autotools
    after:
      - desktop-gtk3
      - gtk-layer-shell
      - mate-menu
      - mate-common
      - mate-desktop
      - mate-weather
    source: https://github.com/wmww/mate-panel.git
    source-branch: wayland-snap
    source-depth: 1
    autotools-configure-parameters:
      - --with-in-process-applets=all
      - --enable-wayland
      - --disable-x11
      - --prefix=/usr
    build-environment:
      - ACLOCAL_FLAGS: -I ${SNAPCRAFT_STAGE}/usr/share/aclocal/
      - CFLAGS: -Wno-deprecated-declarations
    # As of core20, the autotools plugin refuses to run ./autogen.sh anymore
    # ./configure must exist, but it can just be a symlink to ./autogen.sh
    # We remove any old ./configure that may exist so ln doesn't fail
    # If mate-desktop starts providing a ./configre this whole mess can be dropped
    override-build: |
      ln -sf $SNAPCRAFT_PART_BUILD/autogen.sh $SNAPCRAFT_PART_BUILD/configure
      snapcraftctl build
    build-packages:
      - yelp-tools
      - libwnck-3-dev
      - librsvg2-dev
      - librsvg2-bin
    stage-packages:
      - libice6
      - libwnck-3-0
      - libsm6
      - libxres1
      - libstartup-notification0
      - libxcb-util1

  mir-git:
    plugin: cmake
    source: https://github.com/MirServer/mir.git
    source-branch: master
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DMIR_ENABLE_TESTS=OFF
      - -DMIR_PLATFORM='gbm-kms;eglstream-kms;x11;wayland'
    # TODO Add a prime section so development headers and such don't get primed
    build-packages:
      - build-essential
      - xsltproc
      - protobuf-compiler
      - libdrm-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libgl1-mesa-dev
      - libgbm-dev
      - libglm-dev
      - libprotobuf-dev
      - libgoogle-glog-dev
      - liblttng-ust-dev
      - libxkbcommon-dev
      - libumockdev-dev
      - umockdev
      - libudev-dev
      - libgtest-dev
      - google-mock
      - libxml++2.6-dev
      - libglib2.0-dev
      - libfreetype6-dev
      - libevdev-dev
      - libinput-dev
      - uuid-dev
      - python3
      - nettle-dev
      - libcapnp-dev
      - capnproto
      - libepoxy-dev
      - python3-pil
      - libxcb-composite0-dev
      - libxcursor-dev
      - libyaml-cpp-dev
      - systemtap-sdt-dev
      - eglexternalplatform-dev
      - libnvidia-egl-wayland-dev
        # Below are the ones that had a version bump in core20
      - libboost1.71-dev
      - libboost-date-time1.71-dev
      - libboost-program-options1.71-dev
      - libboost-system1.71-dev
      - libboost-filesystem1.71-dev
      - libboost-iostreams1.71-dev
    stage-packages:
      - libdrm2
      - libegl1-mesa
      - libgles2
      - libwayland-server0
      - libxcursor1
      - libxfixes3
      - libxrender1
      - libfreetype6
      - libgflags2.2
      - libgoogle-glog0v5
      - liblttng-ust0
      - libunwind8
      - liburcu6
      - libwayland-egl1-mesa
      - libxcb-composite0
      - libxcb-render0
      - libevdev-dev
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libwacom2
      - libxkbcommon0
      - uuid-runtime
      - libglibmm-2.4-1v5
      - libsigc++-2.0-0v5
      - libxml++2.6-2v5
      - libnvidia-egl-wayland1
      #- inotify-tools
        # Below are the ones that had a version bump in core20
      - libboost-iostreams1.71.0
      - libboost-system1.71.0
      - libboost-filesystem1.71.0
      - libboost-program-options1.71.0
      - libcapnp-0.7.0
      - libprotobuf-lite17
      - libyaml-cpp0.6

  mirco:
    after: [mir-git]
    plugin: meson
    source: https://github.com/wmww/mirco.git
    source-depth: 1
    build-environment:
      - LDFLAGS: -Wl,-rpath=/root/stage/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:/build/mate-wayland/stage/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    meson-parameters:
      - --buildtype=release
    build-packages:
      - pkg-config

  files:
    plugin: dump
    source: files

  mesa:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - no-patchelf # Otherwise snapcraft may strip the build ID and cause the driver to crash

  snap-out:
    # Used by the panel (as a binary, not a library) to clean the environment of snap variables when launching an external program
    plugin: rust
    source: https://github.com/wmww/snap-out.git
    source-depth: 1
