name: mate-wayland
version: mate-wayland
version-script: |
  LANG=C apt-cache policy libmircore1 | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/egmde'$(git --git-dir=parts/egmde/src/.git rev-list --count HEAD)'-mir\1/p'
summary: A prototype for the MATE desktop running on Wayland with Mir
description: A prototype for the MATE desktop running on Wayland with Mir
confinement: classic
grade: devel
base: core18

apps:
  mate-wayland:
    command: bin/mate-wayland.launcher
    environment:
      # Prep for Mir
      MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      EGMDE_LAUNCH_PREFIX: "env -u __EGL_VENDOR_LIBRARY_DIRS --"

parts:
  ppa-mir-release:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:mir-team/release
      # We shouldn't need to install stuff here, but it seems to fix intermittent build failures
      sudo apt --assume-yes install libmiral-dev mir-graphics-drivers-desktop
      sudo apt clean
      snapcraftctl pull

  egmde:
    after: [ppa-mir-release]
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
    stage-packages:
      - mir-graphics-drivers-desktop
      - libmiral3

  launcher:
    plugin: dump
    source: glue
    organize:
      mate-wayland.launcher: bin/
      mate-wayland.desktop: bin/

  mesa:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
