name: mate-wayland
version: git
summary: A prototype for the MATE desktop running on Wayland with Mir
description: A prototype for the MATE desktop running on Wayland with Mir
confinement: classic
grade: devel
base: core18

apps:
  mate-wayland:
    command: bin/mate-wayland.launcher
    environment:
      # Prep for Mir
      MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

parts:
  mate-common:
    plugin: autotools
    source: https://github.com/mate-desktop/mate-common.git
    build-environment:
      - ACLOCAL_FLAGS: -I /root/stage/share/aclocal/

  mate-desktop:
    after: [mate-common]
    plugin: autotools
    source: https://github.com/mate-desktop/mate-desktop.git
    build-environment:
      - prefix: /root/stage/
    #    - ACLOCAL_FLAGS: -I /root/stage/share/aclocal/
    #    - PKG_CONFIG_PATH: /usr/local/lib/pkgconfig/
    build-packages:
      - intltool
      - gtk-doc-tools
      - gobject-introspection
      - libdconf-dev
      - libgtk-3-dev
      - iso-codes
    stage-packages:
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxrandr2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcairo2
      - libcairo-gobject2
      - libepoxy0
      - libgraphite2-3
      - libgtk-3-0
      - libgdk-pixbuf2.0-0

  mir-git:
    plugin: cmake
    source: https://github.com/MirServer/mir.git
    source-branch: mate-support
    source-depth: 1
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DMIR_ENABLE_TESTS=OFF
      - -DMIR_PLATFORM=mesa-kms;mesa-x11
    # TODO Add a prime section so development headers and such don't get primed
    build-packages:
      - build-essential
      - xsltproc
      - libboost-dev
      - libboost-date-time-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - protobuf-compiler
      - libdrm-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libgl1-mesa-dev
      - libgbm-dev
      - libglm-dev
      - libprotobuf-dev
      - libgoogle-glog-dev
      - liblttng-ust-dev
      - libxkbcommon-dev
      - libumockdev-dev
      - umockdev
      - libudev-dev
      - libgtest-dev
      - google-mock
      - libxml++2.6-dev
      - libglib2.0-dev
      - libfreetype6-dev
      - libevdev-dev
      - libinput-dev
      - uuid-dev
      - python3
      - nettle-dev
      - libcapnp-dev
      - capnproto
      - libepoxy-dev
      - python3-pil
      - libxcb-composite0-dev
      - libxcursor-dev
      - libyaml-cpp-dev
    stage-packages:
      - libdrm2
      - libegl1-mesa
      - libgbm1
      - libgles2
      - libwayland-server0
      - libxcursor1
      - libxfixes3
      - libxrender1
      - libboost-iostreams1.65.1
      - libfreetype6
      - libgflags2.2
      - libgoogle-glog0v5
      - liblttng-ust0
      - libunwind8
      - liburcu6
      - libwayland-egl1-mesa
      - libxcb-composite0
      - libxcb-render0
      - libyaml-cpp0.5v5
      - libcapnp-0.6.1
      - libboost-system1.65.1
      - libboost-filesystem1.65.1
      - libboost-program-options1.65.1
      - libevdev-dev
      - libgudev-1.0-0
      - libinput10
      - libmtdev1
      - libprotobuf-lite10
      - libwacom2
      - libxkbcommon0

  mirco:
    after: [mir-git]
    plugin: cmake
    source: https://github.com/wmww/mirco.git
    source-depth: 1
    build-packages:
      - pkg-config

  launcher:
    plugin: dump
    source: glue
    organize:
      mate-wayland.launcher: bin/
      mate-wayland.desktop: bin/

  mesa:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
