#!/bin/sh

mkdir -p /usr/share/wayland-sessions/
cp $SNAP/usr/share/wayland-sessions/mate-wayland.desktop /usr/share/wayland-sessions/mate-wayland.desktop

# Ensure Wayland support is available for Qt apps
if [ "$(sed -Ene 's/^ID=(.*)/\1/p' /etc/os-release)" = "ubuntu" ]; then
  apt --assume-yes install qtwayland5
elif [ "$(sed -Ene 's/^ID=(.*)/\1/p' /etc/os-release)" = "fedora" ]; then
  dnf --assumeyes  install qt5-qtwayland
fi
