#!/bin/sh

mkdir -p /usr/share/wayland-sessions/
cp $SNAP/bin/mate-wayland.desktop /usr/share/wayland-sessions/mate-wayland.desktop

# Ensure Wayland support is available for Qt apps
if [ "$(sed -Ene 's/^ID=(.*)/\1/p' /etc/os-release)" = "ubuntu" ]; then
  apt --assume-yes install qtwayland5
elif [ "$(sed -Ene 's/^ID=(.*)/\1/p' /etc/os-release)" = "fedora" ]; then
  dnf --assumeyes  install qt5-qtwayland
fi

if [ "$(readlink -f /snap/core18/current/lib64/ld-linux-x86-64.so.2)" = "/lib/x86_64-linux-gnu/ld-2.27.so" ]; then
  echo "Working around broken /snap/core18/current/lib64/ld-linux-x86-64.so.2 symlink"
  if [ ! -f /lib/x86_64-linux-gnu/ld-2.27.so ]; then
    ln -s /snap/core18/current/lib/x86_64-linux-gnu/ld-2.27.so /lib/x86_64-linux-gnu/ld-2.27.so
  fi
fi

if [ "$(readlink -f /snap/core18/current/lib64/ld-linux-x86-64.so.2)" = "" ]; then
  echo "Working around broken /snap/core18/current/lib64/ld-linux-x86-64.so.2 symlink"
  if [ ! -d "/lib/x86_64-linux-gnu/" ]; then
    mkdir /lib/x86_64-linux-gnu/
  fi
  if [ ! -f /lib/x86_64-linux-gnu/ld-2.27.so ]; then
    ln -s /snap/core18/current/lib/x86_64-linux-gnu/ld-2.27.so /lib/x86_64-linux-gnu/ld-2.27.so
  fi
fi

# I know the logic looks weird, but this happens on 19.04
if [ "$(readlink -f /snap/core18/current/lib64/ld-linux-x86-64.so.2)" = "/usr/lib/x86_64-linux-gnu/ld-2.27.so" ]; then
  echo "Working around broken /snap/core18/current/lib64/ld-linux-x86-64.so.2 symlink"
  if [ ! -f /lib/x86_64-linux-gnu/ld-2.27.so ]; then
    ln -s /snap/core18/current/lib/x86_64-linux-gnu/ld-2.27.so /lib/x86_64-linux-gnu/ld-2.27.so
  fi
fi
